### ISSUE TITLE
pop_back & deque

### ISSUE THREAD

**Issue by manoharreddyporeddy** [datastructures-js/queue#22]
`deque` which allows `push_front` & `pop_back`, is a very useful data structure
when it comes to inserting/ deleting either ends

https://en.cppreference.com/w/cpp/container/deque

---

we can create a new data structure with name `deque`
or 
allow one more param in constructor of queue, that enables it to work like `deque` and has similar operation to `pop_back`

what are your views on this? thanks

**Comment by eyas-ranjous** [comment]
Hi Manohar, this would be a very nice and useful addition to the project, so thanks for suggesting it. I gave it a thought and will build that as an independent data structure in a new repo, it makes more sense. Will keep the issue here opened till the release of the datastructures-js/deque

**Comment by manoharreddyporeddy** [comment]
@eyas-ranjous 

Sure Eyas
New repo makes more sense.
- It won't disturb current implementation, and can grow independently.
- But on the other hand, some duplication will be there, which is totally fine. Just that we need to take-in the fixes of one to the other when there are potential improvements that are common to each other.

1
And while solving a problem elsewhere
I created a base structure for the Deque, and posted impleted to my github link given below.

2
My Deque implementation is very basic:
- Not optimal in terms of memory hence speed, etc. ( but it passed all tests of a Hard question, to begin with )
- I have not used push_front function, but might work ( there is a comment for the same in the code )
- Since I moved from C++ to JavaScript, out of habit I used C++ snake_case_covention for function names, so might not be perfect for camelCase JavaScript, for example: may be, it should be pushBack() instead of push_back(), etc.

3
Also, I can write a bit of code :), so do let me know if you need help in some tasks. I like very trivial or very difficult tasks :)

4
And thanks for building Deque

---

Deque implementation / Github link:
- https://github.com/manoharreddyporeddy/math-advanced-data-structures-and-algorithms/blob/master/javascript-deque.js

Deque implementation usage / My solution elsewhere:
- https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/discuss/1627030/javascript-862-shortest-subarray-with-sum-at-least-k

---

**Comment by eyas-ranjous** [comment]
v1 released https://www.npmjs.com/package/@datastructures-js/deque
